import Celebrities from '../components/Celebrities'
import ContactCta from '../components/contact/ContactCta'
import DoctorStats from '../components/doctor/DoctorStats'
import LandbotFacade from '../components/LandbotFacade'
import PageBanner from '../components/PageBanner'
import { seoFor } from '../seo/pages'

/**
 * /ai-hair-transplant-cost-calculator/ -- the AI assessment and cost estimate.
 *
 * NO GENERATED MARKER, DELIBERATELY. scripts/gen-pages.mjs overwrites any page
 * file still carrying `// GENERATED by scripts/gen-pages.mjs`.
 *
 * ONE OF THE SIX noindex AD LANDING PAGES -- no canonical, not in the sitemap.
 * scripts/verify-seo.mjs asserts both, so nothing here may touch src/seo/.
 *
 * COPY: neofollicle-seo-backup/pages/ai-hair-transplant-cost-calculator/. The
 * captured page is the h1, one lede line, a three-step "How Does It Work?",
 * the doctor's stat band and two review videos. All of it is below, verbatim
 * where it is copy.
 *
 * THE TOOL IS THE SAME BOT AS /hair-assessment/. The captured page's own CTAs
 * point back at itself and its h1 calls the flow an "AI Hair Assessment Report
 * & Cost Calculator" -- it is the marketing front for the assessment, not a
 * second tool. hair-conditions-we-treat's capture confirms it: its button
 * reads "AI Hair Analysis & HT Cost Calculator" and points at /hair-assessment.
 * So the same Landbot config is mounted here rather than bouncing an ad click
 * through a second page to reach it.
 *
 * The stat band and testimonials are the shared components the doctor page and
 * the home page already use -- this page's captured versions of both are the
 * same content, so rendering anything else here would be a second copy to keep
 * in step.
 */
export default function AiHairTransplantCostCalculator() {
  return (
    <>
      <PageBanner
        crumbs={[{ label: 'Home', to: '/' }, { label: 'AI Cost Calculator' }]}
        image="/hero.webp"
        title={
          seoFor('ai-hair-transplant-cost-calculator').h1 ??
          'Try Our Free AI Hair Assessment Report & Cost Calculator'
        }
      />

      <LandbotFacade
        configUrl="https://storage.googleapis.com/landbot.pro/v3/H-3082458-C4Q4SEVC54EBQLPP/index.json"
        heading="How Does It Work?"
        /* The capture's lede line, verbatim. */
        lede="We use artificial intelligence to calculate the approximate cost of hair transplantation."
        /* The capture's three h4s, verbatim as titles. */
        steps={[
          {
            title: 'Take A Photo',
            body: 'Upload clear photos of your hairline, crown and donor area.',
          },
          {
            title: 'Wait for the AI to analyze your images!',
            body: 'The assessment reviews your pattern, density and stage of hair loss.',
          },
          {
            title: 'Get Your Report',
            body: 'Receive your report and an approximate cost by email.',
          },
        ]}
        startLabel="Start Free AI Assessment"
        note="Takes about 3 minutes. No payment required."
      />

      <DoctorStats />
      <Celebrities />
      <ContactCta />
    </>
  )
}
