// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function AlopeciaAreataTreatmentInBangalore() {
  return <PagePlaceholder slug="alopecia-areata-treatment-in-bangalore" />
}
