import Celebrities from '../components/Celebrities'
import ContactCta from '../components/contact/ContactCta'
import ContactMap from '../components/contact/ContactMap'
import DoctorStats from '../components/doctor/DoctorStats'
import LpFaq from '../components/lp/LpFaq'
import PageBanner from '../components/PageBanner'
import TreatmentGallery from '../components/TreatmentGallery'
import TreatmentSectionView from '../components/treatment/sections'
import WhyNeoFollicle from '../components/WhyNeoFollicle'
import { LP_CELEBRITIES, LP_FACILITIES, LP_FAQ, LP_SERVICES } from '../content/lp/shared'
import { seoFor } from '../seo/pages'

/**
 * /best-hair-transplant-clinic-lp/ -- the clinic ad landing page.
 *
 * NO GENERATED MARKER, DELIBERATELY. scripts/gen-pages.mjs overwrites any page
 * file still carrying `// GENERATED by scripts/gen-pages.mjs`.
 *
 * ONE OF THE SIX noindex AD LANDING PAGES -- no canonical, not in the sitemap.
 * scripts/verify-seo.mjs asserts both, so nothing here may touch src/seo/.
 * NOT IN src/config/nav.ts either: it is reached from an ad, and adding it
 * would change the captured header/footer that verify-seo check 8 walks.
 *
 * ASSEMBLED, NOT DESIGNED. Its capture is a recombination of sections the site
 * already has -- celebrities, services, results, the doctor's numbers, reviews,
 * why-choose, facilities, FAQ, map, CTA -- so every band below is either an
 * existing prop-less component or a `TreatmentSection` rendered through the
 * shared section renderer. Nothing new was drawn for this page, which is what
 * keeps it in the site's design language for free.
 *
 * SECTION ORDER is the capture's, with one change: the services list now LINKS
 * to each treatment page (`linkGrid`). The old LP named five services and
 * linked to none of them.
 *
 * GROUNDS ALTERNATE by hand here rather than by TreatmentPage's groundFor(),
 * because the imported components carry their own: Services is a `primary`
 * band, DoctorStats likewise, and Celebrities/TreatmentGallery/WhyNeoFollicle
 * are all `base`. The grounds passed below are chosen so no two adjacent bands
 * share a fill.
 */
export default function BestHairTransplantClinicLp() {
  return (
    <>
      <PageBanner
        crumbs={[{ label: 'Home', to: '/' }, { label: 'Best Hair Transplant Clinic' }]}
        image="/hero.webp"
        title={seoFor('best-hair-transplant-clinic-lp').h1 ?? 'Best Hair Transplant Clinic in Bangalore'}
      >
        {/* The capture's sub-headline, verbatim. */}
        <p className="text-body-lg text-white/90">Natural Results. Trusted Care.</p>
      </PageBanner>

      <TreatmentSectionView
        ground="surface"
        section={{
          kind: 'linkGrid',
          heading: 'Hair Transplant Services We Offer',
          items: LP_SERVICES,
        }}
      />

      <TreatmentGallery />

      <TreatmentSectionView
        ground="surface"
        section={{
          kind: 'personalities',
          heading: 'Sandalwood Celebrities Trust Neo Follicle Hair Transplant Clinic',
          people: LP_CELEBRITIES,
        }}
      />

      <DoctorStats />
      <Celebrities />

      <TreatmentSectionView ground="surface" section={LP_FACILITIES} />

      <WhyNeoFollicle />

      <LpFaq
        name="clinic-lp-faq"
        heading="FAQs on Hair Transplant in Bangalore"
        items={LP_FAQ}
        ground="surface"
      />

      <ContactMap />
      <ContactCta />
    </>
  )
}
