import PageBanner from '../components/PageBanner'
import ContactBooking from '../components/contact/ContactBooking'
import ContactCta from '../components/contact/ContactCta'
import ContactMap from '../components/contact/ContactMap'
import ContactWhyVisit from '../components/contact/ContactWhyVisit'
import { seoFor } from '../seo/pages'

/**
 * /contact-us/ -- the site's conversion page.
 *
 * NO GENERATED MARKER, DELIBERATELY. scripts/gen-pages.mjs overwrites any page
 * file still carrying `// GENERATED by scripts/gen-pages.mjs`, so re-adding
 * that line would make the next `npm run gen:pages` replace this page with a
 * PagePlaceholder stub. home.tsx, the doctor page and the treatment pages all
 * do the same.
 *
 * PagePlaceholder is not used for the other reason too: it renders
 * seoFor(slug).h1, which would put a second <h1> on the page under the
 * banner's.
 *
 * THE HEAD IS FROZEN; THE BODY IS OURS. scripts/verify-seo.mjs asserts this
 * page's <title>, meta description, canonical, robots and entire JSON-LD graph
 * byte-for-byte against neofollicle-seo-backup. Nothing in src/seo/pages.ts or
 * src/seo/schema/contact-us.json may be touched from here without failing
 * `npm run verify`. That graph is this page's most valuable asset: ContactPage
 * + MedicalClinic + two appointment ContactPoints + Physician, all already
 * indexed.
 *
 * THIS PAGE WAS ALREADY THE TARGET OF EVERY CTA ON THE SITE and was still a
 * placeholder. headerCta, StickyActionBar, SidebarCta, DoctorCta,
 * TreatmentsCta, the footer pill and content/treatments/ctas.ts BOOK all point
 * at /contact-us/. See the note in src/config/nav.ts: linking it from the
 * header and footer was the SEO audit's P1 fix, because the page was
 * indexable, sitemapped and declared ContactPage with zero inbound internal
 * links.
 *
 * THE SLUG IS /contact-us/, NOT THE DOC'S /contact. Content doc PAGE 5 proposes
 * `/contact`, but /contact-us/ is the canonical, sitemapped, indexed URL and
 * its trailing slash is P0-PRESERVE. Same call hair-loss-treatment-in-bangalore
 * records for its own doc-vs-capture URL split.
 *
 * COPY: content/treatments/Neo Follicle Website Content-5.md, PAGE 5.
 * DESIGN: folixa-design-reference/pages/appointment/ (sections 2, 3, 6 and 7),
 * with the map from .../pages/contact/ section 5.
 *
 *   SECTION 1 Hero          -> PageBanner + ContactBooking's h2
 *   SECTION 2 Contact Cards -> ContactBooking
 *   SECTION 3 Clinic Hours  -> ContactBooking's fourth card (see its docblock
 *                              for why the JSON-LD's hours win over the doc's)
 *   SECTION 4 Why Visit     -> ContactWhyVisit
 *   SECTION 5 Contact Form  -> ContactBooking, via the shared ContactUs form
 *   SECTION 6 Final CTA     -> ContactCta
 *
 * The map has no section in the doc, but both the captured page and the
 * reference carry one, and an address with no map on a clinic's contact page
 * is a gap rather than a simplification.
 */
export default function ContactUs() {
  return (
    <>
      <PageBanner
        crumbs={[{ label: 'Home', to: '/' }, { label: 'Contact Us' }]}
        /*
          "Contact Us" -- the h1 the captured page ranks with, read from the
          PageSeo record rather than written as a literal so it cannot drift.
          Same call our-blogs.tsx makes. The doc's hero line, "Visit Neo
          Follicle Hair Transplant Clinic", is the h2 below.
        */
        title={seoFor('contact-us').h1 ?? 'Contact Us'}
        /*
          Shared with the home hero and the blog archive -- the only clinic
          photograph in public/. A dedicated reception or exterior shot at
          /contact/banner.webp would serve this page better; see the note in
          BlogListing, which is waiting on the same asset.
        */
        image="/hero.webp"
      />

      <ContactBooking />
      <ContactWhyVisit />
      <ContactMap />
      <ContactCta />
    </>
  )
}
