// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function DrSandeepMahapatraHairTransplantSurgeon() {
  return <PagePlaceholder slug="dr-sandeep-mahapatra-hair-transplant-surgeon" />
}
