// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function EyebrowRestorationInBangalore() {
  return <PagePlaceholder slug="eyebrow-restoration-in-bangalore" />
}
