// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function FemaleHairTransplantInBangalore() {
  return <PagePlaceholder slug="female-hair-transplant-in-bangalore" />
}
