// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function HairTransplantCostInBangalore() {
  return <PagePlaceholder slug="hair-transplant-cost-in-bangalore" />
}
