// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import BlogPost from '../components/BlogPost'
import post from '../content/posts/hair-transplant-recovery-timeline'

export default function HairTransplantRecoveryTimeline() {
  return <BlogPost post={post} />
}
