// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import BlogPost from '../components/BlogPost'
import post from '../content/posts/hair-transplant-india-international-patients'

export default function HairTransplantIndiaInternationalPatients() {
  return <BlogPost post={post} />
}
