import TreatmentPage from '../components/treatment/TreatmentPage'
import data from '../content/treatments/hair-conditions-we-treat'

/**
 * /hair-conditions-we-treat/ -- the conditions index.
 *
 * NO GENERATED MARKER, DELIBERATELY. scripts/gen-pages.mjs overwrites any page
 * file still carrying `// GENERATED by scripts/gen-pages.mjs`, so re-adding
 * that line would replace this page with a PagePlaceholder stub on the next
 * `npm run gen:pages`. home.tsx, contact-us.tsx, the doctor page and every
 * treatment page do the same.
 *
 * PagePlaceholder is dropped for the other reason too: it renders
 * seoFor(slug).h1, which would put a second <h1> under the hero's.
 *
 * Everything else is in src/content/treatments/hair-conditions-we-treat.ts --
 * see its docblock for why this page rides the treatment renderer, and for the
 * P1 internal-linking reason it exists at all.
 */
export default function HairConditionsWeTreat() {
  return <TreatmentPage data={data} />
}
