// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import BlogPost from '../components/BlogPost'
import post from '../content/posts/natural-hairline-design-hair-transplants'

export default function NaturalHairlineDesignHairTransplants() {
  return <BlogPost post={post} />
}
