import ContactUs from '../components/ContactUs'
import PageBanner from '../components/PageBanner'
import { seoFor } from '../seo/pages'

/**
 * /nft-brochure/ -- the brochure download gate.
 *
 * NO GENERATED MARKER, DELIBERATELY. scripts/gen-pages.mjs overwrites any page
 * file still carrying `// GENERATED by scripts/gen-pages.mjs`.
 *
 * PagePlaceholder is dropped for the other reason too: it renders
 * seoFor(slug).h1, which would put a second <h1> under the banner's.
 *
 * COPY: neofollicle-seo-backup/pages/nft-brochure/. The whole captured body is
 * the h1 and one instruction line -- everything else on that page was nav and
 * footer chrome. Both are carried verbatim below.
 *
 * THE FORM IS THE SHARED ContactUs COMPONENT, relabelled. It already carries
 * the field set, the validation, the lead endpoint (FORMS.leadEndpoint) and
 * the design resolved from the reference -- so a second, nearly
 * identical form component for this one page would be a copy to maintain, not
 * a feature. Only `submitLabel` and the surrounding copy differ.
 *
 * ON SUBMIT the funnel continues to /nft-brochure-thank-you/, which is the
 * captured behaviour and is what `successTo` below does. ContactUs otherwise
 * stays put and shows its inline "sent" message -- the right default for the
 * home and contact-us forms, but it would have left the brochure thank-you
 * page with nothing at all linking to it.
 *
 * NOTE ON THE BROCHURE EMAIL. These leads land
 * in the lead sheet tagged Form = "brochure" (scripts/apps-script/Code.gs). But
 * that script only notifies the clinic -- it does NOT email the visitor the
 * brochure, so the thank-you page's "we have sent the download link to your
 * email" is still a promise nothing keeps. Add it to Code.gs when the brochure
 * PDF has a hosted URL.
 */
export default function NftBrochure() {
  return (
    <>
      <PageBanner
        crumbs={[{ label: 'Home', to: '/' }, { label: 'NFT Brochure' }]}
        /*
          Shared with the home hero, the blog archive, contact-us and the legal
          pages -- the only clinic photograph in public/.
        */
        image="/hero.webp"
        title={seoFor('nft-brochure').h1 ?? 'Download Neofollicle Hair Transplant Brochure'}
      />

      <ContactUs
        eyebrow="Free Download"
        heading="Get the Neo Follicle Hair Transplant Brochure"
        /* The capture's instruction line, verbatim. */
        lede="Fill up the below form to download the NFT Brochure. Once you fill up the form, we will send you an email with link to download the NFT brochure."
        submitLabel="Download Brochure"
        successTo="/nft-brochure-thank-you/"
        formId="brochure"
      />
    </>
  )
}
