// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import BlogPost from '../components/BlogPost'
import post from '../content/posts/prp-vs-gfc-for-hair-loss'

export default function PrpVsGfcForHairLoss() {
  return <BlogPost post={post} />
}
