// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function SamplePage() {
  return <PagePlaceholder slug="sample-page" />
}
