import TreatmentPage from '../components/treatment/TreatmentPage'
import data from '../content/treatments/scalp-micropigmentation-in-bangalore'

/**
 * NO GENERATED MARKER, DELIBERATELY. scripts/gen-pages.mjs overwrites any page
 * file still carrying `// GENERATED by scripts/gen-pages.mjs`, so re-adding
 * that line would make the next `npm run gen:pages` replace this page with a
 * PagePlaceholder stub. home.tsx and the ten surgical pages do the same.
 *
 * PagePlaceholder is not used for the other reason too: it renders
 * seoFor(slug).h1, which would put a second <h1> on the page under the hero's.
 */
export default function ScalpMicropigmentationInBangalore() {
  return <TreatmentPage data={data} />
}
