// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function ThankYouLp() {
  return <PagePlaceholder slug="thank-you-lp" />
}
