// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import PagePlaceholder from '../components/PagePlaceholder'

export default function VideoGallery() {
  return <PagePlaceholder slug="video-gallery" />
}
