// GENERATED by scripts/gen-pages.mjs. Do not edit by hand.
import BlogPost from '../components/BlogPost'
import post from '../content/posts/why-hair-transplants-fail'

export default function WhyHairTransplantsFail() {
  return <BlogPost post={post} />
}
