// GENERATED by scripts/gen-posts.mjs from neofollicle-seo-backup/. Do not edit by hand.
// Regenerate with: npm run gen:posts
//
// The listing page's data source: every post field except the body, so importing
// it costs a few KB rather than the whole corpus. Newest first, matching the
// order the old /our-blogs/ page listed them in.
import type { PostSummary } from './types'

export const postSummaries: PostSummary[] = [
  {
    "slug": "why-hair-transplants-fail",
    "path": "/why-hair-transplants-fail/",
    "title": "Why Hair Transplants Fail: Causes, Signs, and Prevention",
    "excerpt": "Understand why hair transplants fail, the visible signs of poor results, and how safe graft handling, ethical donor planning, and surgeon-led protocols help protect long-term hair growth.",
    "summary": "Hair transplants usually fail because of poor graft handling, unsafe extraction, wrong implantation depth, or untreated ongoing hair loss. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr. Sandeep Mahapatra follows surgeon-supervised protocols to protect graft survival, donor area safety, and natural-looking results.",
    "category": "Hair Transplant Safety",
    "datePublished": "2026-07-07T06:13:55+05:30",
    "dateModified": "2026-07-07T06:13:57+05:30",
    "readingMinutes": 14,
    "card": {
      "src": "/blog/why-hair-transplants-fail.webp",
      "alt": "Why Hair Transplants Fail",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/why-hair-transplants-fail-hero.webp",
      "alt": "Why Hair Transplants Fail",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "medical-treatments-for-hair-loss",
    "path": "/medical-treatments-for-hair-loss/",
    "title": "Medical Treatments for Hair Loss: A Dermatologist’s Guide",
    "excerpt": "Understand how dermatologist-guided medicines, PRP, GFC, Exosome Therapy, QR678, and nutrition correction can help control hair loss before considering a transplant.",
    "summary": "Medical treatments for hair loss can slow thinning, strengthen weak follicles, and delay or reduce the need for a hair transplant when started early. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr. Sandeep Mahapatra creates personalized plans using medicines, PRP, GFC, Exosome Therapy, QR678, nutrition correction, and scalp evaluation.",
    "category": "Hair Loss Treatment",
    "datePublished": "2026-07-05T08:30:35+05:30",
    "dateModified": "2026-07-05T08:30:38+05:30",
    "readingMinutes": 14,
    "card": {
      "src": "/blog/medical-treatments-for-hair-loss.webp",
      "alt": "Medical Treatments for Hair Loss",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/medical-treatments-for-hair-loss-hero.webp",
      "alt": "Medical Treatments for Hair Loss",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "unethical-practices-in-hair-transplantation",
    "path": "/unethical-practices-in-hair-transplantation/",
    "title": "Be Aware of Unethical Practices in Hair Transplantation",
    "excerpt": "Learn how to identify unethical hair transplant practices such as ghost surgeons, fake graft counts, misleading results, and hidden costs. Dr. Sandeep Mahapatra explains what true transparency looks like at Neo Follicle in Bangalore.",
    "summary": "Unethical hair transplant practices include ghost surgeons, fake graft counts, misleading before-and-after photos, and hidden role changes during surgery. These practices can harm donor hair, reduce graft survival, and create unnatural or permanent damage. Dr. Sandeep Mahapatra at Neo Follicle Hair Transplant Clinic recommends asking who performs each surgical step upfront.",
    "category": "Patient Education",
    "datePublished": "2026-07-03T09:27:44+05:30",
    "dateModified": "2026-07-05T08:15:50+05:30",
    "readingMinutes": 12,
    "card": {
      "src": "/blog/unethical-practices-in-hair-transplantation.webp",
      "alt": "Unethical Practices in Hair Transplant",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/unethical-practices-in-hair-transplantation-hero.webp",
      "alt": "Unethical Practices in Hair Transplant",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "fue-hair-transplant-bangalore",
    "path": "/fue-hair-transplant-bangalore/",
    "title": "The Complete Guide to FUE Hair Transplant",
    "excerpt": "FUE hair transplant is a modern technique that restores hair without a linear scar. In this guide, Dr. Sandeep Mahapatra explains the step-by-step FUE procedure, recovery, benefits, risks, graft survival, and what patients in Bangalore should expect.",
    "summary": "FUE hair transplant is a modern, minimally invasive way to restore natural-looking hair without a linear scar. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra, Hair Transplant Surgeon, carefully extracts and implants individual grafts to protect roots and improve survival. A detailed consultation helps confirm suitability and realistic results.",
    "category": "FUE Hair Transplant",
    "datePublished": "2026-07-01T07:50:51+05:30",
    "dateModified": "2026-07-03T11:53:38+05:30",
    "readingMinutes": 15,
    "card": {
      "src": "/blog/fue-hair-transplant-bangalore.webp",
      "alt": "The Complete Guide to FUE Hair Transplant",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/fue-hair-transplant-bangalore-hero.webp",
      "alt": "The Complete Guide to FUE Hair Transplant",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "gfc-vs-exosome-vs-qr678-hair-treatment",
    "path": "/gfc-vs-exosome-vs-qr678-hair-treatment/",
    "title": "GFC vs Exosome vs QR678 Hair Treatment",
    "excerpt": "Compare GFC, Exosome and QR678 hair treatments for hair loss. Learn how each works, who benefits most, safety differences, session needs and when a hair transplant may be better, with insights from Neo Follicle Hair Transplant Clinic, Bangalore.",
    "summary": "GFC, Exosome and QR678 are advanced non-surgical hair loss treatments, but the best choice depends on your stage of thinning and follicle activity. They work by sending growth signals to weak, living follicles, not dead bald areas. Consult Dr Sandeep Mahapatra at Neo Follicle Hair Transplant Clinic in Bangalore for diagnosis-based guidance.",
    "category": "Hair Loss Treatment",
    "datePublished": "2026-06-29T07:25:22+05:30",
    "dateModified": "2026-07-03T11:57:35+05:30",
    "readingMinutes": 17,
    "card": {
      "src": "/blog/gfc-vs-exosome-vs-qr678-hair-treatment.webp",
      "alt": "GFC vs Exosome Vs QR678 Hair Treatment",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/gfc-vs-exosome-vs-qr678-hair-treatment-hero.webp",
      "alt": "GFC vs Exosome Vs QR678 Hair Treatment",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "donor-area-planning-hair-transplant",
    "path": "/donor-area-planning-hair-transplant/",
    "title": "Why Donor Area Planning Is Critical in Hair Transplant",
    "excerpt": "Donor area planning is the foundation of a safe hair transplant. Learn why donor hair is limited, how over-harvesting can cause permanent thinning, and how careful graft planning protects long-term, natural-looking results.",
    "summary": "Donor area planning is the most critical step in a safe hair transplant because donor hair is limited and does not grow back once extracted. Poor planning or over-harvesting can permanently thin the back of the scalp. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra plans graft use carefully for long-term natural results.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-27T05:00:00+05:30",
    "dateModified": "2026-06-27T05:00:00+05:30",
    "readingMinutes": 16,
    "card": {
      "src": "/blog/donor-area-planning-hair-transplant.webp",
      "alt": "Why Donor Area Planning is Critical in Hair Transplant",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/donor-area-planning-hair-transplant-hero.webp",
      "alt": "Why Donor Area Planning is Critical in Hair Transplant",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "hair-transplant-for-receding-hairline",
    "path": "/hair-transplant-for-receding-hairline/",
    "title": "Hair Transplant for a Receding Hairline: What Every Patient Should Know",
    "excerpt": "Learn when a receding hairline needs medical treatment and when a hair transplant is the right step. Dr. Sandeep Mahapatra explains hairline timing, donor planning, medical stabilization, and natural restoration at Neo Follicle, Bangalore.",
    "summary": "A receding hairline may need medical treatment first, and hair transplant only when hair loss is stable and donor planning is safe. Dr Sandeep Mahapatra, Hair Transplant Surgeon at Neo Follicle Hair Transplant Clinic in Bangalore, explains that early surgery on active hair loss can look unnatural. Start with expert evaluation and long-term planning.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-25T06:00:00+05:30",
    "dateModified": "2026-06-25T06:00:00+05:30",
    "readingMinutes": 10,
    "card": {
      "src": "/blog/hair-transplant-for-receding-hairline.webp",
      "alt": "Hair Transplant for a Receeding Hairline",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/hair-transplant-for-receding-hairline-hero.webp",
      "alt": "Hair Transplant for a Receeding Hairline",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "how-many-grafts-do-i-need-for-hair-transplant",
    "path": "/how-many-grafts-do-i-need-for-hair-transplant/",
    "title": "How Many Grafts Do I Need for a Hair Transplant?",
    "excerpt": "Learn how hair transplant grafts are calculated based on baldness stage, donor density, hair thickness, and coverage goals. Dr. Sandeep Mahapatra explains grafts vs hair strands, safe donor planning, and red flags to avoid before surgery.",
    "summary": "The number of grafts needed for a hair transplant depends on baldness stage, bald area size, donor strength, hair thickness, and desired coverage. Dr Sandeep Mahapatra, Hair Transplant Surgeon at Neo Follicle Hair Transplant Clinic in Bangalore, explains that safe graft calculation protects both results and donor area. Always choose transparent assessment over inflated graft promises.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-23T07:00:00+05:30",
    "dateModified": "2026-06-23T07:00:00+05:30",
    "readingMinutes": 12,
    "card": {
      "src": "/blog/how-many-grafts-do-i-need-for-hair-transplant.webp",
      "alt": "How many grafts do I need for hair transplant",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/how-many-grafts-do-i-need-for-hair-transplant-hero.webp",
      "alt": "How many grafts do I need for hair transplant",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "fue-vs-direct-hair-implantation",
    "path": "/fue-vs-direct-hair-implantation/",
    "title": "FUE vs. Direct Hair Implantation: Which Is Better for You?",
    "excerpt": "Compare FUE and Direct Hair Implantation in simple terms. Learn how both techniques work, where they differ, who they suit best, and why the right choice depends on your baldness grade, donor area, density goals, and long-term hair plan.",
    "summary": "FUE and Direct Hair Implantation can both deliver natural results; neither is universally better for every patient. The right choice depends on baldness grade, donor strength, graft count, hairline density goals, and how the grafts are implanted. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra recommends a personalized scalp assessment before choosing.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-21T08:00:00+05:30",
    "dateModified": "2026-06-21T08:00:00+05:30",
    "readingMinutes": 13,
    "card": {
      "src": "/blog/fue-vs-direct-hair-implantation.webp",
      "alt": "FUE vs DHI Hair Transplant",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/fue-vs-direct-hair-implantation-hero.webp",
      "alt": "FUE vs DHI Hair Transplant",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "is-hair-transplant-permanent",
    "path": "/is-hair-transplant-permanent/",
    "title": "Is a Hair Transplant Permanent?",
    "excerpt": "Understand why a hair transplant can be permanent, how donor dominance protects transplanted follicles, and why native hair may still need long-term care. Dr Sandeep Mahapatra explains the real science behind lifelong hair transplant results.",
    "summary": "A hair transplant can be permanent when healthy follicles are taken from the true safe donor zone. These follicles are naturally resistant to DHT and keep that resistance even after being moved to thinning areas. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra plans each case to protect long-term density.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-19T06:00:00+05:30",
    "dateModified": "2026-06-19T06:00:00+05:30",
    "readingMinutes": 12,
    "card": {
      "src": "/blog/is-hair-transplant-permanent.webp",
      "alt": "Is Hair Transplant Permanent",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/is-hair-transplant-permanent-hero.webp",
      "alt": "Is Hair Transplant Permanent",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "hair-transplant-myths-vs-facts",
    "path": "/hair-transplant-myths-vs-facts/",
    "title": "Hair Transplant Myths vs. Facts: Setting the Record Straight",
    "excerpt": "Dr. Sandeep Mahapatra busts common hair transplant myths and explains the real facts about safety, donor hair, pain, recovery, results, cost, and long-term care so patients can make informed, confident treatment decisions.",
    "summary": "Most hair transplant myths are false when the procedure is planned and performed by a qualified surgeon. Hair transplant works at the scalp-skin level using your own donor hair, so it does not affect the brain, eyes, or body organs. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra offers safe, evidence-based guidance.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-17T07:00:00+05:30",
    "dateModified": "2026-06-17T07:00:00+05:30",
    "readingMinutes": 20,
    "card": {
      "src": "/blog/hair-transplant-myths-vs-facts.webp",
      "alt": "Hair Transplant Myth Vs Facts",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/hair-transplant-myths-vs-facts-hero.webp",
      "alt": "Hair Transplant Myth Vs Facts",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "hair-transplant-india-international-patients",
    "path": "/hair-transplant-india-international-patients/",
    "title": "The Ultimate Guide to Hair Transplants in India for International Patients",
    "excerpt": "International patients can safely plan a hair transplant in India with the right clinic, surgeon, travel support, and follow-up care. This guide explains why Bangalore and Neo Follicle offer trusted, English-speaking hair restoration care.",
    "summary": "International patients can safely plan a hair transplant in India when they choose an experienced surgeon, sterile clinic, clear communication, and structured follow-up care. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra combines surgical expertise with international patient support. Start with a virtual consultation to confirm suitability, graft planning, travel timeline, and recovery needs.",
    "category": "Hair Transplant Medical Tourism",
    "datePublished": "2026-06-16T07:00:00+05:30",
    "dateModified": "2026-06-16T07:00:00+05:30",
    "readingMinutes": 20,
    "card": {
      "src": "/blog/hair-transplant-india-international-patients.webp",
      "alt": "Hait Transplant in India for International Patients",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/hair-transplant-india-international-patients-hero.webp",
      "alt": "Hait Transplant in India for International Patients",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "hair-transplant-recovery-timeline",
    "path": "/hair-transplant-recovery-timeline/",
    "title": "The Ultimate Hair Transplant Recovery Timeline: What to Expect Month by Month",
    "excerpt": "Understand the complete hair transplant recovery timeline, from early scabs and shedding to new growth, density improvement, and final results. Dr. Sandeep Mahapatra explains what is normal month by month and when to seek medical advice.",
    "summary": "Hair transplant recovery takes 12 to 18 months, with early scabs, temporary shedding, slow regrowth, and gradual density improvement being normal. This happens because transplanted follicles need time to settle, rest, and restart natural growth cycles. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra guides patients through each recovery stage.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-15T07:00:00+05:30",
    "dateModified": "2026-06-15T07:00:00+05:30",
    "readingMinutes": 22,
    "card": {
      "src": "/blog/hair-transplant-recovery-timeline.webp",
      "alt": "Hair Transplant Recovery Timeline",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/hair-transplant-recovery-timeline-hero.webp",
      "alt": "Hair Transplant Recovery Timeline",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "female-hair-loss",
    "path": "/female-hair-loss/",
    "title": "Understanding Female Hair Loss: Root Causes, Diagnosis, and Proven Treatments",
    "excerpt": "A complete guide for international patients planning a hair transplant in India, covering why Bangalore and Neo Follicle offer safe, English-speaking care, travel support, transparent planning, sterile protocols, and digital follow-up with Dr Sandeep.",
    "summary": "Female hair loss is common, medically understandable, and often controllable once the root cause is diagnosed. Widening part lines, PCOS, thyroid imbalance, stress and nutritional deficiencies all present differently. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra diagnoses before treating.",
    "category": "Female Hair Loss",
    "datePublished": "2026-06-14T08:00:00+05:30",
    "dateModified": "2026-06-14T08:00:00+05:30",
    "readingMinutes": 21,
    "card": {
      "src": "/blog/female-hair-loss.webp",
      "alt": "Understanding Female Hair Loss",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/female-hair-loss-hero.webp",
      "alt": "Understanding Female Hair Loss",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "is-hair-transplant-painful",
    "path": "/is-hair-transplant-painful/",
    "title": "Is a Hair Transplant Painful? What to Honestly Expect Before, During, and After",
    "excerpt": "Hair transplant pain is usually far less than patients fear. Learn what to expect before, during, and after the procedure, from local anesthesia pinches to mild recovery soreness, with honest guidance from Neo Follicle Hair Transplant Clinic in Bangalore.",
    "summary": "A hair transplant is usually not painful after local anesthesia, except for a brief initial pinch during numbing. Dr Sandeep Mahapatra, Hair Transplant Surgeon at Neo Follicle Hair Transplant Clinic in Bangalore, explains that the scalp stays numb during extraction and implantation. Mild soreness after surgery is manageable with prescribed medicines and proper aftercare.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-13T07:00:00+05:30",
    "dateModified": "2026-06-13T07:00:00+05:30",
    "readingMinutes": 12,
    "card": {
      "src": "/blog/is-hair-transplant-painful.webp",
      "alt": "Is Hair Transplant Painful",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/is-hair-transplant-painful-hero.webp",
      "alt": "Is Hair Transplant Painful",
      "width": 1600,
      "height": 837
    }
  },
  {
    "slug": "natural-hairline-design-hair-transplants",
    "path": "/natural-hairline-design-hair-transplants/",
    "title": "The Art and Science of Natural Hairline Design in Hair Transplants",
    "excerpt": "Learn how natural hairline design in hair transplants blends medical precision with artistry. Dr. Sandeep Mahapatra explains age-appropriate planning, soft irregularities, single-hair grafts, and key mistakes to avoid for natural, undetectable results.",
    "summary": "Natural hairline design in hair transplants creates a soft, age-appropriate, undetectable look instead of a straight or artificial appearance. Dr Sandeep Mahapatra, Hair Transplant Surgeon at Neo Follicle Hair Transplant Clinic in Bangalore, uses facial proportions, single-hair grafts, and natural irregularities to design hairlines that age well.",
    "category": "Hair Transplant",
    "datePublished": "2026-06-12T09:00:00+05:30",
    "dateModified": "2026-06-12T09:00:00+05:30",
    "readingMinutes": 22,
    "card": {
      "src": "/blog/natural-hairline-design-hair-transplants.webp",
      "alt": "The Art & Science Of Natural Hair Line Design in Hair Transplants",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/natural-hairline-design-hair-transplants-hero.webp",
      "alt": "The Art & Science Of Natural Hair Line Design in Hair Transplants",
      "width": 1536,
      "height": 1024
    }
  },
  {
    "slug": "prp-vs-gfc-for-hair-loss",
    "path": "/prp-vs-gfc-for-hair-loss/",
    "title": "PRP vs GFC for Hair Loss: What Is the Difference and Which Is Best for You?",
    "excerpt": "PRP and GFC are regenerative hair loss treatments that use your own blood, but they work differently. This blog explains their preparation, comfort, sessions, results, ideal candidates, and when a hair transplant may be the better option.",
    "summary": "PRP and GFC both help early hair thinning by strengthening weak, living follicles, but GFC is a more refined growth-factor treatment. PRP releases growth factors after injection, while GFC delivers concentrated growth factors prepared beforehand. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra can assess which suits your stage.",
    "category": "Hair Loss Treatment",
    "datePublished": "2026-06-12T09:00:00+05:30",
    "dateModified": "2026-06-12T09:00:00+05:30",
    "readingMinutes": 20,
    "card": {
      "src": "/blog/prp-vs-gfc-for-hair-loss.webp",
      "alt": "PRP Vs GFC Treatment Which is the one for you",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/prp-vs-gfc-for-hair-loss-hero.webp",
      "alt": "PRP Vs GFC Treatment Which is the one for you",
      "width": 1536,
      "height": 1024
    }
  },
  {
    "slug": "male-pattern-hair-loss",
    "path": "/male-pattern-hair-loss/",
    "title": "Understanding Male Pattern Hair Loss: Stages, Science, and Solutions",
    "excerpt": "Male pattern hair loss is a common genetic condition linked to DHT sensitivity. Learn the Norwood stages, causes, early signs, proven treatments like minoxidil, PRP/GFC, and when FUE hair transplant may help restore natural-looking hair.",
    "summary": "Male pattern hair loss is a common genetic condition that can be managed when diagnosed early. It happens when DHT-sensitive follicles gradually shrink, causing thinning at the hairline and crown. At Neo Follicle Hair Transplant Clinic in Bangalore, Dr Sandeep Mahapatra, Hair Transplant Surgeon, can guide you on medical treatment, PRP/GFC, or FUE restoration.",
    "category": "Hair Loss",
    "datePublished": "2026-06-12T09:00:00+05:30",
    "dateModified": "2026-06-12T09:00:00+05:30",
    "readingMinutes": 18,
    "card": {
      "src": "/blog/male-pattern-hair-loss.webp",
      "alt": "Norwood Scale Male Pattern Baldness",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/male-pattern-hair-loss-hero.webp",
      "alt": "Norwood Scale Male Pattern Baldness",
      "width": 1600,
      "height": 900
    }
  },
  {
    "slug": "how-to-choose-the-best-hair-transplant-clinic-bangalore",
    "path": "/how-to-choose-the-best-hair-transplant-clinic-bangalore/",
    "title": "How to Choose the Best Hair Transplant Clinic in Bangalore",
    "excerpt": "Choosing the best hair transplant clinic in Bangalore means looking beyond price. Learn what to check before surgery, including surgeon involvement, graft transparency, hygiene standards, safety protocols, realistic results, and red flags to avoid.",
    "summary": "Choosing the best hair transplant clinic in Bangalore means checking surgeon involvement, safety protocols, graft transparency, and realistic results—not just price. Dr Sandeep Mahapatra, Hair Transplant Surgeon at Neo Follicle Hair Transplant Clinic in Bangalore, recommends choosing a clinic that examines your donor area carefully and offers honest, long-term follow-up.",
    "category": "Hair Transplant Clinic Selection",
    "datePublished": "2026-06-12T09:00:00+05:30",
    "dateModified": "2026-06-12T09:00:00+05:30",
    "readingMinutes": 20,
    "card": {
      "src": "/blog/how-to-choose-the-best-hair-transplant-clinic-bangalore.webp",
      "alt": "How to Choose the Best Hair Transplant Clinic in Bangalore",
      "width": 1200,
      "height": 628
    },
    "hero": {
      "src": "/blog/how-to-choose-the-best-hair-transplant-clinic-bangalore-hero.webp",
      "alt": "How to Choose the Best Hair Transplant Clinic in Bangalore",
      "width": 1600,
      "height": 900
    }
  }
]

export const postSummaryBySlug: Record<string, PostSummary> = Object.fromEntries(
  postSummaries.map((p) => [p.slug, p]),
)
