#!/usr/bin/env node
/**
 * Ports the captured SEO layer out of ../neofollicle-seo-backup and appends
 * metadata for pages authored after that snapshot from content/seo/.
 *
 * Source of truth:
 *   01-SEO-MASTER.csv                     one row per URL, every meta field
 *   site-level/sitemap-post-type-*.xml    lastmod values
 *   pages/<slug>/schema.jsonld            captured JSON-LD
 *   content/seo/*.json                    authored page metadata + JSON-LD
 *   content/seo/overrides.json            rewritten titles/descriptions/robots
 *   src/config/site.ts                    the site-wide JSON-LD entities
 *
 * Every graph goes through normalizeGraph() (scripts/seo/entity-graph.mjs):
 * one @graph per page, the config-built #website/#organization/#clinic/
 * #physician in place of the page's own copies, no duplicate @ids.
 *
 * Writes:
 *   src/seo/pages.ts          all captured and authored PageSeo records
 *   src/seo/schema/*.json     one graph per page
 *
 * Re-runnable. Nothing here is hand-edited afterwards -- edit the backup or this
 * script, then `npm run gen:seo`.
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { ASSETS, BRAND, SEO } from '../src/config/site.ts'
import { normalizeGraph } from './seo/entity-graph.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const backup = path.join(root, 'neofollicle-seo-backup')
const authoredDir = path.join(root, 'content', 'seo')
const outDir = path.join(root, 'src', 'seo')
const schemaDir = path.join(outDir, 'schema')

const ORIGIN = SEO.origin

/** Minimal RFC4180 parser -- descriptions contain commas and embedded quotes. */
function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ } else { inQuotes = false }
      } else field += c
    } else if (c === '"') inQuotes = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = '' }
    else if (c === '\r') { /* skip */ }
    else field += c
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row) }
  const header = rows.shift()
  return rows
    .filter(r => r.length === header.length)
    .map(r => Object.fromEntries(header.map((h, i) => [h, r[i]])))
}

/** slug -> route path. Only `home` and `uncategorized` deviate from /<slug>/. */
function routePath(row) {
  const p = row.url.startsWith(ORIGIN) ? row.url.slice(ORIGIN.length) : row.url
  return p || '/'
}

/** lastmod per URL, harvested from the three captured sitemaps. */
function readLastmods() {
  const map = new Map()
  for (const f of ['sitemap-post-type-page.xml', 'sitemap-post-type-post.xml', 'sitemap-taxonomy-category.xml']) {
    const xml = fs.readFileSync(path.join(backup, 'site-level', f), 'utf8')
    for (const m of xml.matchAll(/<url>\s*<loc>([^<]+)<\/loc>\s*(?:<lastmod>([^<]+)<\/lastmod>)?/g)) {
      map.set(m[1], m[2] ?? null)
    }
  }
  return map
}

const rows = parseCsv(fs.readFileSync(path.join(backup, '01-SEO-MASTER.csv'), 'utf8'))
const lastmods = readLastmods()

fs.mkdirSync(schemaDir, { recursive: true })
for (const f of fs.readdirSync(schemaDir)) fs.unlinkSync(path.join(schemaDir, f))

/** slug -> raw JSON-LD blocks, normalised and written once all pages are known. */
const graphs = new Map()

const capturedPages = rows.map(r => {
  const src = path.join(backup, 'pages', r.slug, 'schema.jsonld')
  if (!fs.existsSync(src)) throw new Error(`missing schema.jsonld for ${r.slug}`)
  graphs.set(r.slug, JSON.parse(fs.readFileSync(src, 'utf8')))

  return {
    slug: r.slug,
    path: routePath(r),
    type: r.type,
    title: r.title,
    description: r.meta_description,
    // The 36 Slim SEO body dumps + the 2 with no description at all. Ported
    // verbatim per the P0 rule, flagged so `pages.filter(p => p.needsRewrite)`
    // is the P1 worklist. See seo-audit.md section 1.
    needsRewrite: r.desc_is_autogenerated === 'True' || r.meta_description === '',
    descFlagReason: r.desc_flag_reason || null,
    // The 6 noindex ad landing pages genuinely have no canonical tag. Do not
    // synthesise one -- absence is the captured state.
    canonical: r.canonical || null,
    robots: r.robots,
    og: {
      title: r['og:title'] || null,
      description: r['og:description'] || null,
      url: r['og:url'] || null,
      type: r['og:type'] || null,
      image: r['og:image'] || null,
      siteName: r['og:site_name'] || null,
      locale: r['og:locale'] || null,
    },
    twitter: {
      card: r['twitter:card'] || null,
      title: r['twitter:title'] || null,
    },
    h1: r.h1 || null,
    inSitemap: r.sitemap_included === 'True',
    lastmod: lastmods.get(r.url) ?? null,
  }
})

const authored = fs.existsSync(authoredDir)
  ? fs.readdirSync(authoredDir)
      .filter((file) => file.endsWith('.json') && file !== 'overrides.json')
      .sort()
      .map((file) => JSON.parse(fs.readFileSync(path.join(authoredDir, file), 'utf8')))
  : []

for (const entry of authored) {
  if (!entry.seo?.slug || !Array.isArray(entry.schema)) {
    throw new Error('content/seo entries require an seo record and schema array')
  }
  graphs.set(entry.seo.slug, entry.schema)
}

const overridesFile = path.join(authoredDir, 'overrides.json')
const overrides = fs.existsSync(overridesFile)
  ? JSON.parse(fs.readFileSync(overridesFile, 'utf8'))
  : {}

/** ISO date of the last commit touching a page's source, for pages the capture had no lastmod for. */
function gitLastmod(slug) {
  const files = [`src/pages/${slug}.tsx`, `content/seo/${slug}.json`].filter((f) => fs.existsSync(path.join(root, f)))
  if (!files.length) return null
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cI', '--', ...files], { cwd: root, encoding: 'utf8' }).trim()
    return out || null
  } catch {
    return null
  }
}

/**
 * Overrides, then the fields every page derives from its own title and
 * description: og/twitter mirror them, and every page gets its generated
 * 1200x630 share card (scripts/gen-og-images.mjs) as og:image.
 */
function finalise(page) {
  const o = overrides[page.slug] ?? {}
  for (const key of Object.keys(o)) {
    if (!['title', 'description', 'robots', 'inSitemap'].includes(key)) {
      throw new Error(`overrides.json: unknown field "${key}" on ${page.slug}`)
    }
  }
  if (!graphs.has(page.slug)) throw new Error(`overrides.json: no page "${page.slug}"`)

  const title = o.title ?? page.title
  const description = o.description ?? page.description
  const image = `${ORIGIN}${ASSETS.ogCardDir}${page.slug}.jpg`
  return {
    ...page,
    title,
    description,
    needsRewrite: o.description ? false : page.needsRewrite,
    descFlagReason: o.description ? null : page.descFlagReason,
    robots: o.robots ?? page.robots,
    og: {
      ...page.og,
      title,
      description,
      url: page.og.url ?? `${ORIGIN}${page.path}`,
      image,
      imageAlt: page.h1 ?? title,
      imageWidth: ASSETS.ogImageSize.width,
      imageHeight: ASSETS.ogImageSize.height,
      siteName: BRAND.name,
      locale: SEO.locale,
    },
    twitter: { card: SEO.twitterCard, title, description, image },
    inSitemap: o.inSitemap ?? page.inSitemap,
    lastmod: page.lastmod ?? gitLastmod(page.slug),
  }
}

for (const slug of Object.keys(overrides)) {
  if (!slug.startsWith('$') && !graphs.has(slug)) throw new Error(`overrides.json: no page "${slug}"`)
}
delete overrides.$comment

const pages = [...capturedPages, ...authored.map((entry) => entry.seo)].map(finalise)

/**
 * Keeps the page's own WebPage node in step with an overridden title and
 * description, and gives indexable pages without one a Home > Page breadcrumb.
 */
for (const page of pages) {
  const url = `${ORIGIN}${page.path}`
  const blocks = graphs.get(page.slug)
  const hasCrumbs = JSON.stringify(blocks).includes('"BreadcrumbList"')
  const extra = []
  if (!hasCrumbs && page.path !== '/' && page.inSitemap) {
    extra.push({
      '@type': 'BreadcrumbList',
      '@id': `${url}#breadcrumblist`,
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${ORIGIN}/` },
        { '@type': 'ListItem', position: 2, name: page.h1 ?? page.title, item: url },
      ],
    })
  }
  const [block] = normalizeGraph(blocks, extra)
  for (const node of block['@graph']) {
    if (node['@id'] === `${url}#webpage` || node['@id'] === `${url}#contactpage`) {
      node.name = page.title
      node.description = page.description
    }
  }
  fs.writeFileSync(path.join(schemaDir, `${page.slug}.json`), `${JSON.stringify([block], null, 1)}\n`)
}

const duplicateSlugs = pages.filter((page, index) => pages.findIndex((p) => p.slug === page.slug) !== index)
const duplicatePaths = pages.filter((page, index) => pages.findIndex((p) => p.path === page.path) !== index)
if (duplicateSlugs.length || duplicatePaths.length) {
  throw new Error(`duplicate SEO slug/path: ${[...duplicateSlugs, ...duplicatePaths].map((p) => p.slug).join(', ')}`)
}

const banner = `// GENERATED by scripts/gen-seo.mjs from neofollicle-seo-backup/ and content/seo/. Do not edit by hand.
// Regenerate with: npm run gen:seo
`

const body = `${banner}
export type PageSeo = {
  slug: string
  /** Route path, trailing slash preserved. This is P0 -- changing it forces a redirect. */
  path: string
  type: 'page' | 'post' | 'category'
  title: string
  description: string
  /** true for the 38 auto-generated or missing descriptions. See reports/seo-audit.md section 1. */
  needsRewrite: boolean
  descFlagReason: string | null
  /** null on the 6 noindex landing pages, which carry no canonical tag. */
  canonical: string | null
  robots: string
  og: {
    title: string | null
    description: string | null
    url: string | null
    type: string | null
    image: string | null
    imageAlt: string | null
    imageWidth: number
    imageHeight: number
    siteName: string | null
    locale: string | null
  }
  twitter: { card: string | null; title: string | null; description: string | null; image: string | null }
  h1: string | null
  inSitemap: boolean
  lastmod: string | null
}

export const SITE_ORIGIN = '${ORIGIN}'

export const pages: PageSeo[] = ${JSON.stringify(pages, null, 2)}

export const pageBySlug: Record<string, PageSeo> = Object.fromEntries(
  pages.map((p) => [p.slug, p]),
)

export const pageByPath: Record<string, PageSeo> = Object.fromEntries(
  pages.map((p) => [p.path, p]),
)

export function seoFor(slug: string): PageSeo {
  const p = pageBySlug[slug]
  if (!p) throw new Error(\`No SEO record for slug "\${slug}"\`)
  return p
}
`

fs.writeFileSync(path.join(outDir, 'pages.ts'), body)

const indexable = pages.filter(p => p.inSitemap).length
const flagged = pages.filter(p => p.needsRewrite).length
console.log(`gen-seo: ${pages.length} pages -> src/seo/pages.ts`)
console.log(`         ${indexable} in sitemap, ${pages.length - indexable} noindex`)
console.log(`         ${flagged} descriptions flagged needsRewrite`)
console.log(`         ${fs.readdirSync(schemaDir).length} JSON-LD graphs -> src/seo/schema/`)
