#!/usr/bin/env node
/**
 * Ports the captured SEO layer out of ../neofollicle-seo-backup and appends
 * metadata for pages authored after that snapshot from content/seo/.
 *
 * Source of truth:
 *   01-SEO-MASTER.csv                     one row per URL, every meta field
 *   site-level/sitemap-post-type-*.xml    lastmod values
 *   pages/<slug>/schema.jsonld            captured JSON-LD, copied verbatim
 *   content/seo/*.json                    authored page metadata + JSON-LD
 *
 * Writes:
 *   src/seo/pages.ts          all captured and authored PageSeo records
 *   src/seo/schema/*.json     one graph per page
 *
 * Re-runnable. Nothing here is hand-edited afterwards -- edit the backup or this
 * script, then `npm run gen:seo`.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const backup = path.join(root, 'neofollicle-seo-backup')
const authoredDir = path.join(root, 'content', 'seo')
const outDir = path.join(root, 'src', 'seo')
const schemaDir = path.join(outDir, 'schema')

// Keep in sync with SEO.origin in src/config/site.ts. Node ESM scripts cannot
// import the .ts config without a loader, so this copy stays for now.
const ORIGIN = 'https://neofollicletransplant.com'

/** Minimal RFC4180 parser -- descriptions contain commas and embedded quotes. */
function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ } else { inQuotes = false }
      } else field += c
    } else if (c === '"') inQuotes = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = '' }
    else if (c === '\r') { /* skip */ }
    else field += c
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row) }
  const header = rows.shift()
  return rows
    .filter(r => r.length === header.length)
    .map(r => Object.fromEntries(header.map((h, i) => [h, r[i]])))
}

/** slug -> route path. Only `home` and `uncategorized` deviate from /<slug>/. */
function routePath(row) {
  const p = row.url.startsWith(ORIGIN) ? row.url.slice(ORIGIN.length) : row.url
  return p || '/'
}

/** lastmod per URL, harvested from the three captured sitemaps. */
function readLastmods() {
  const map = new Map()
  for (const f of ['sitemap-post-type-page.xml', 'sitemap-post-type-post.xml', 'sitemap-taxonomy-category.xml']) {
    const xml = fs.readFileSync(path.join(backup, 'site-level', f), 'utf8')
    for (const m of xml.matchAll(/<url>\s*<loc>([^<]+)<\/loc>\s*(?:<lastmod>([^<]+)<\/lastmod>)?/g)) {
      map.set(m[1], m[2] ?? null)
    }
  }
  return map
}

const rows = parseCsv(fs.readFileSync(path.join(backup, '01-SEO-MASTER.csv'), 'utf8'))
const lastmods = readLastmods()

fs.mkdirSync(schemaDir, { recursive: true })
for (const f of fs.readdirSync(schemaDir)) fs.unlinkSync(path.join(schemaDir, f))

const capturedPages = rows.map(r => {
  // Copy the JSON-LD graph across untouched. Every file is a one-element array
  // wrapping a @graph; the nodes cross-reference each other by absolute @id, so
  // reformatting or rewriting URLs here would break the graph.
  const src = path.join(backup, 'pages', r.slug, 'schema.jsonld')
  if (!fs.existsSync(src)) throw new Error(`missing schema.jsonld for ${r.slug}`)
  fs.copyFileSync(src, path.join(schemaDir, `${r.slug}.json`))

  return {
    slug: r.slug,
    path: routePath(r),
    type: r.type,
    title: r.title,
    description: r.meta_description,
    // The 36 Slim SEO body dumps + the 2 with no description at all. Ported
    // verbatim per the P0 rule, flagged so `pages.filter(p => p.needsRewrite)`
    // is the P1 worklist. See seo-audit.md section 1.
    needsRewrite: r.desc_is_autogenerated === 'True' || r.meta_description === '',
    descFlagReason: r.desc_flag_reason || null,
    // The 6 noindex ad landing pages genuinely have no canonical tag. Do not
    // synthesise one -- absence is the captured state.
    canonical: r.canonical || null,
    robots: r.robots,
    og: {
      title: r['og:title'] || null,
      description: r['og:description'] || null,
      url: r['og:url'] || null,
      type: r['og:type'] || null,
      image: r['og:image'] || null,
      siteName: r['og:site_name'] || null,
      locale: r['og:locale'] || null,
    },
    twitter: {
      card: r['twitter:card'] || null,
      title: r['twitter:title'] || null,
    },
    h1: r.h1 || null,
    inSitemap: r.sitemap_included === 'True',
    lastmod: lastmods.get(r.url) ?? null,
  }
})

const authored = fs.existsSync(authoredDir)
  ? fs.readdirSync(authoredDir)
      .filter((file) => file.endsWith('.json'))
      .sort()
      .map((file) => JSON.parse(fs.readFileSync(path.join(authoredDir, file), 'utf8')))
  : []

for (const entry of authored) {
  if (!entry.seo?.slug || !Array.isArray(entry.schema)) {
    throw new Error('content/seo entries require an seo record and schema array')
  }
  fs.writeFileSync(
    path.join(schemaDir, `${entry.seo.slug}.json`),
    `${JSON.stringify(entry.schema, null, 1)}\n`,
  )
}

const pages = [...capturedPages, ...authored.map((entry) => entry.seo)]
const duplicateSlugs = pages.filter((page, index) => pages.findIndex((p) => p.slug === page.slug) !== index)
const duplicatePaths = pages.filter((page, index) => pages.findIndex((p) => p.path === page.path) !== index)
if (duplicateSlugs.length || duplicatePaths.length) {
  throw new Error(`duplicate SEO slug/path: ${[...duplicateSlugs, ...duplicatePaths].map((p) => p.slug).join(', ')}`)
}

const banner = `// GENERATED by scripts/gen-seo.mjs from neofollicle-seo-backup/ and content/seo/. Do not edit by hand.
// Regenerate with: npm run gen:seo
`

const body = `${banner}
export type PageSeo = {
  slug: string
  /** Route path, trailing slash preserved. This is P0 -- changing it forces a redirect. */
  path: string
  type: 'page' | 'post' | 'category'
  title: string
  description: string
  /** true for the 38 auto-generated or missing descriptions. See reports/seo-audit.md section 1. */
  needsRewrite: boolean
  descFlagReason: string | null
  /** null on the 6 noindex landing pages, which carry no canonical tag. */
  canonical: string | null
  robots: string
  og: {
    title: string | null
    description: string | null
    url: string | null
    type: string | null
    image: string | null
    siteName: string | null
    locale: string | null
  }
  twitter: { card: string | null; title: string | null }
  h1: string | null
  inSitemap: boolean
  lastmod: string | null
}

export const SITE_ORIGIN = '${ORIGIN}'

export const pages: PageSeo[] = ${JSON.stringify(pages, null, 2)}

export const pageBySlug: Record<string, PageSeo> = Object.fromEntries(
  pages.map((p) => [p.slug, p]),
)

export const pageByPath: Record<string, PageSeo> = Object.fromEntries(
  pages.map((p) => [p.path, p]),
)

export function seoFor(slug: string): PageSeo {
  const p = pageBySlug[slug]
  if (!p) throw new Error(\`No SEO record for slug "\${slug}"\`)
  return p
}
`

fs.writeFileSync(path.join(outDir, 'pages.ts'), body)

const indexable = pages.filter(p => p.inSitemap).length
const flagged = pages.filter(p => p.needsRewrite).length
console.log(`gen-seo: ${pages.length} pages -> src/seo/pages.ts`)
console.log(`         ${indexable} in sitemap, ${pages.length - indexable} noindex`)
console.log(`         ${flagged} descriptions flagged needsRewrite`)
console.log(`         ${fs.readdirSync(schemaDir).length} JSON-LD graphs -> src/seo/schema/`)
